language: dart
sudo: false
dart:
  - dev
before_script:
  - chmod +x run_tests.sh
script: ./run_tests.sh
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.pub-cache
notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - ltackmann@gmail.com
