name: dice
version: 2.0.0
author: Lars Tackmann <lars@solvr.io>
description: Lightweight dependency injection framework for Dart.
homepage: https://github.com/ltackmann/dice

environment:
  sdk: '>=2.0.0-dev.51.0 <2.0.0'

dependencies:
  logging: ^0.11.0

dev_dependencies:
  #browser: ^0.10.0

  logging_handlers: ^0.8.0
  console_log_handler: ^1.0.0

  test: ^1.2.0
